language: node_js
node_js:
- '8'
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 182.92.131.201
install: # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - source ./travis_init.sh # 执行指定的 shell 脚本来做初始化
script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - npm run build # 生成dist
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv #解密ssh私钥
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@182.92.131.201 -o StrictHostKeyChecking=no 'cd ~ && ./hello.sh' #通过ssh连接自己的远端服务器
- scp -o stricthostkeychecking=no -i ~/.ssh/id_rsa -r ./dist travis@182.92.131.201:/home/travis/vbook #通过scp将打包后的dist文件传输到自己的服务器上
