language: node_js
node_js:
- '8'
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 182.92.131.201
install:
  - source ./travis_init.sh
script:
  - npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@182.92.131.201 -o StrictHostKeyChecking=no 'cd ~ && ./hello.sh'
- scp -o stricthostkeychecking=no -i ~/.ssh/id_rsa -r ./dist travis@182.92.131.201:/home/travis/vbook
