language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
  - npm install
script:
  - npm run test
addons:
  ssh_known_hosts:
  - 8.140.151.101
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@8.140.151.101 -o StrictHostKeyChecking=no 'cd ~ && ./hello.sh'
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
